apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name | quote }}
  labels:
    app: {{ .Values.app.label | quote }}
spec:
  replicas: {{ .Values.replicaCount | quote }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.app.label | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.label | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000

          # Environment variables
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.host | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.db }}"
            - name: POSTGRES
              value: {{ .Values.postgres.enabled | quote }}
          
          # Volume mount for file uploads
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads

          # ✅ Health checks
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3

          # Resources to manage usage
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "100m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "300m"

      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc
