apiVersion: batch/v1
kind: Job
metadata:
  name: create-superuser
spec:
  template:
    spec:
      containers:
        - name: create-superuser
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          command: ["sh", "-c", "python manage.py shell < create_superuser.py"]
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
      restartPolicy: Never
  backoffLimit: 5
