apiVersion: v1
kind: PersistentVolume
metadata:
  name: yum-app-pv
spec:
  capacity:
    storage: {{ .Values.uploads.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/yum-app-uploads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.uploads.storage }}
