apiVersion: apps/v1
kind: Deployment
metadata:
  name: yum-book-app
  labels:
    app: yum-book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yum-book-app
  template:
    metadata:
      labels:
        app: yum-book-app
    spec:
      containers:
        - name: yum-book-app
          image: mgrah/yum-book:latest1 # Change this if you use a different tag/name
          ports:
            - containerPort: 8000
