apiVersion: batch/v1
kind: Job
metadata:
  name: yum-book-migrate
  namespace: yum-book
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: yum-book-migrate
          image: mgrah/yum-book:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES
              value: "true"
            - name: POSTGRES_USER
              value: django
            - name: POSTGRES_PASSWORD
              value: django
            - name: POSTGRES_DB
              value: django
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: DATABASE_URL
              value: postgres://django:django@postgres:5432/django
          command: ["/bin/sh", "-c"]
          args:
            - |
              python manage.py migrate &&
              python create_superuser.py
