apiVersion: v1
kind: Service
metadata:
  name: yum-book-service
  labels:
    app: yum-book
spec:
  type: NodePort
  selector:
    app: yum-book-app
  ports:
    - port: 8000 # Cluster IP port
      targetPort: 8000 # Container port
      nodePort: 30080 # Port exposed on the Minikube host
