replicaCount: 2

image:
  repository: mgrah/yum-book
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000
  nodePort: 30080

app:
  name: yum-book-app
  label: yum-book

serviceAccount:
  create: false
  name: ""
