replicaCount: 2

image:
  repository: mgrah/yum-book
  tag: latest
  pullPolicy: Always

service:
  name: yum-book-service
  selector:
    app: yum-book
  labels:
    app: yum-book
  type: NodePort
  port: 8000
  nodePort: 30080
  targetPort: 8000

app:
  name: yum-book-app
  label: yum-book

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false
