name: Build and Push to the Docker Repository

on: 
  push:
    branches: 
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create database
        run: |
          if [ ! -f db.sqlite3 ]; then
            touch db.sqlite3
          fi

      - name: Run migrations
        run: |
          source venv/bin/activate
          python3 manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: |
          source venv/bin/activate
          python manage.py test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mgrah/yum-book:latest
