# name: Test Django Application

# on: 
#   push:
#     branches: 
#       - main
#       - devs
#       - postgres
#     paths-ignore:
#       - 'helm/Chart.yaml'
# jobs:
#   test:
#     if: contains(github.event.head_commit.message, '[skip ci]') == false

#     runs-on: ubuntu-latest

#     steps:
      
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.12' 

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Create database if not exists
#         run: |
#           if [ ! -f db.sqlite3 ]; then
#             touch db.sqlite3
#           fi

#       - name: Run migrations
#         run: |
#           python3 manage.py makemigrations
#           python manage.py migrate

#       - name: Run tests
#         run: python manage.py test
